/*
 * MainFrame.java
 *
 * Created on 02-12-2009, 04:38:22 PM
 */

package mitest;

import java.awt.FlowLayout;
import java.awt.Dimension;
import java.io.File;
import javax.swing.filechooser.FileFilter;
import javax.swing.JFileChooser;

/**
 *
 * @author delaf
 */
public class MainFrame extends javax.swing.JFrame {

    private String titulo;

    /** Creates new form MainFrame */
    public MainFrame(String titulo, int ancho, int alto) {
        // setear titulo
        this.titulo = titulo;
        this.setTitle(titulo);
        this.setMinimumSize(new Dimension(ancho, alto)); // al usar pack() no seria necesario
        initComponents();
        // barra de menus
        this.iniciarButton.setEnabled(false);
        this.siguienteButton.setEnabled(false);
        this.puntajeButton.setEnabled(false);
        this.puntajeButton.setVisible(false); // ocultado, ya que no se suma el puntaje al clickear revisar
        this.ayudaButton.setEnabled(false);
        // panel contenedor
        mainPanel.setLayout(new FlowLayout());
        // agregar ayuda
        this.ayudaButton.setSelected(true);
        this.mostrarAyuda();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        toolBar = new javax.swing.JToolBar();
        abrirButton = new javax.swing.JButton();
        iniciarButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        puntajeButton = new javax.swing.JToggleButton();
        ayudaButton = new javax.swing.JToggleButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        abrirButton.setText("Abrir");
        abrirButton.setFocusable(false);
        abrirButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrirButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        abrirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirButtonActionPerformed(evt);
            }
        });
        toolBar.add(abrirButton);

        iniciarButton.setText("Iniciar");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });
        toolBar.add(iniciarButton);

        siguienteButton.setText("Siguiente >>");
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });
        toolBar.add(siguienteButton);

        puntajeButton.setText("Puntaje");
        puntajeButton.setFocusable(false);
        puntajeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        puntajeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        puntajeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajeButtonActionPerformed(evt);
            }
        });
        toolBar.add(puntajeButton);

        ayudaButton.setText("Ayuda");
        ayudaButton.setFocusable(false);
        ayudaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ayudaButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ayudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaButtonActionPerformed(evt);
            }
        });
        toolBar.add(ayudaButton);

        mainPanel.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ayudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaButtonActionPerformed
        this.mostrarAyuda();
    }//GEN-LAST:event_ayudaButtonActionPerformed

    private void mostrarAyuda () {
        if(ayudaButton.isSelected()) {
            mainPanel.removeAll();
            this.siguienteButton.setEnabled(false);
            this.puntajeButton.setSelected(false);
            mainPanel.add(new Ayuda());
        } else {
            mainPanel.removeAll();
            if(this.pregunta!=null) {
                mainPanel.add(this.pregunta);
                this.siguienteButton.setEnabled(true);
            }
        }
        mainPanel.repaint();
        this.pack();
    }

    private void abrirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirButtonActionPerformed
        //System.out.println(System.getProperty("user.dir"));
        JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
        FileFilter ff = new FileFilter() {
            private String extensions[] = {"txt", "mt"};
            private String description = "MiTeSt extensions: txt, mt";
            public boolean accept(File f) {
                if (f.isDirectory()) return true;
                String name = f.getName().toLowerCase();
                for (int i = extensions.length - 1; i >= 0; i--) {
                    if (name.endsWith(extensions[i])) {
                        return true;
                    }
                }
                return false;
            }
            public String getDescription() { return description; }
        };
        fc.setFileFilter(ff);
        if(fc.showOpenDialog(fc)==0) {
            this.preguntas = new Preguntas(fc.getSelectedFile());
            if(preguntas.cantidad()>0) {
                this.iniciarButton.setEnabled(true);
                this.setTitle(this.titulo+": "+this.preguntas.nombre);
                //this.preguntas.mostrar();
            }
        }
    }//GEN-LAST:event_abrirButtonActionPerformed

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        mainPanel.removeAll(); // sacar instrucciones del frame
        this.iniciarButton.setText("Reiniciar");
        this.siguienteButton.setEnabled(true);
        this.puntajeButton.setEnabled(true);
        this.ayudaButton.setSelected(false);
        this.puntajeButton.setSelected(false);
        this.ayudaButton.setEnabled(true);
        this.npregunta = 0;
        this.puntaje = 0;
        this.siguientePregunta();
    }//GEN-LAST:event_iniciarButtonActionPerformed

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        this.siguientePregunta();
    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void puntajeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajeButtonActionPerformed
        this.mostrarPuntaje();
    }//GEN-LAST:event_puntajeButtonActionPerformed

    private void mostrarPuntaje() {
        if(puntajeButton.isSelected()) {
            mainPanel.removeAll();
            this.siguienteButton.setEnabled(false);
            this.ayudaButton.setSelected(false);
            mainPanel.add(new Puntaje(preguntas.cantidad(), this.puntaje));
        } else {
            mainPanel.removeAll();
            if(this.pregunta!=null) {
                mainPanel.add(this.pregunta);
                this.siguienteButton.setEnabled(true);
            }
        }
        mainPanel.repaint();
        this.pack();
    }

    private void siguientePregunta() {
        // asignar puntaje
        if(pregunta!=null) {
            if(!this.pregunta.revisadaFlag) this.pregunta.revisar();
            this.puntaje += pregunta.puntaje;
        }
        // siguiente pregunta o puntaje si estamos al final
        this.npregunta++;
        if(this.npregunta<=this.preguntas.cantidad()) {
            this.mostrarPregunta(this.npregunta);
        } else {
            this.puntajeButton.setSelected(true);
            this.puntajeButton.setEnabled(false);
            this.ayudaButton.setEnabled(false);
            this.mostrarPuntaje();
        }
    }

    private void mostrarPregunta (int p) {
        if(pregunta!=null) mainPanel.remove(this.pregunta);
        this.pregunta = new Pregunta(this.preguntas.pregunta(p));
        mainPanel.add(this.pregunta);
        mainPanel.repaint();
        this.pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirButton;
    private javax.swing.JToggleButton ayudaButton;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JToggleButton puntajeButton;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables

    private Preguntas preguntas = null;
    private Pregunta pregunta = null;
    private int npregunta;
    private float puntaje;

}
